create table "public"."Games" (
    "id" bigint generated by default as identity not null,
    "gm_id" uuid not null,
    "invite_code" text not null,
    "name" character varying not null,
    "created" timestamp with time zone default now(),
    "players" bigint default '0'::bigint
);


alter table "public"."Games" enable row level security;

create table "public"."JoinedGame" (
    "player_id" uuid not null,
    "game_id" bigint not null
);


alter table "public"."JoinedGame" enable row level security;

create table "public"."SessionNotes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "game_id" bigint,
    "note" text
);


alter table "public"."SessionNotes" enable row level security;

create table "public"."Users" (
    "id" uuid not null
);


alter table "public"."Users" enable row level security;

CREATE UNIQUE INDEX "Games_id_key" ON public."Games" USING btree (id);

CREATE UNIQUE INDEX "Games_invite_code_key" ON public."Games" USING btree (invite_code);

CREATE UNIQUE INDEX "Games_pkey" ON public."Games" USING btree (id);

CREATE UNIQUE INDEX "JoinedGame_pkey" ON public."JoinedGame" USING btree (player_id, game_id);

CREATE UNIQUE INDEX "SessionNotes_pkey" ON public."SessionNotes" USING btree (id);

CREATE UNIQUE INDEX "Users_auth_id_key" ON public."Users" USING btree (id);

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (id);

alter table "public"."Games" add constraint "Games_pkey" PRIMARY KEY using index "Games_pkey";

alter table "public"."JoinedGame" add constraint "JoinedGame_pkey" PRIMARY KEY using index "JoinedGame_pkey";

alter table "public"."SessionNotes" add constraint "SessionNotes_pkey" PRIMARY KEY using index "SessionNotes_pkey";

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

alter table "public"."Games" add constraint "Games_gm_id_fkey" FOREIGN KEY (gm_id) REFERENCES "Users"(id) not valid;

alter table "public"."Games" validate constraint "Games_gm_id_fkey";

alter table "public"."Games" add constraint "Games_id_key" UNIQUE using index "Games_id_key";

alter table "public"."Games" add constraint "Games_invite_code_key" UNIQUE using index "Games_invite_code_key";

alter table "public"."JoinedGame" add constraint "JoinedGame_game_id_fkey" FOREIGN KEY (game_id) REFERENCES "Games"(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."JoinedGame" validate constraint "JoinedGame_game_id_fkey";

alter table "public"."JoinedGame" add constraint "JoinedGame_player_id_fkey" FOREIGN KEY (player_id) REFERENCES "Users"(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."JoinedGame" validate constraint "JoinedGame_player_id_fkey";

alter table "public"."SessionNotes" add constraint "SessionNotes_game_id_fkey" FOREIGN KEY (game_id) REFERENCES "Games"(id) ON DELETE CASCADE not valid;

alter table "public"."SessionNotes" validate constraint "SessionNotes_game_id_fkey";

alter table "public"."Users" add constraint "Users_auth_id_key" UNIQUE using index "Users_auth_id_key";

alter table "public"."Users" add constraint "Users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE RESTRICT ON DELETE SET NULL not valid;

alter table "public"."Users" validate constraint "Users_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_user_on_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public."Users" (id)
  select new.id
  end;
  return new;
end;
$function$
;

grant delete on table "public"."Games" to "anon";

grant insert on table "public"."Games" to "anon";

grant references on table "public"."Games" to "anon";

grant select on table "public"."Games" to "anon";

grant trigger on table "public"."Games" to "anon";

grant truncate on table "public"."Games" to "anon";

grant update on table "public"."Games" to "anon";

grant delete on table "public"."Games" to "authenticated";

grant insert on table "public"."Games" to "authenticated";

grant references on table "public"."Games" to "authenticated";

grant select on table "public"."Games" to "authenticated";

grant trigger on table "public"."Games" to "authenticated";

grant truncate on table "public"."Games" to "authenticated";

grant update on table "public"."Games" to "authenticated";

grant delete on table "public"."Games" to "service_role";

grant insert on table "public"."Games" to "service_role";

grant references on table "public"."Games" to "service_role";

grant select on table "public"."Games" to "service_role";

grant trigger on table "public"."Games" to "service_role";

grant truncate on table "public"."Games" to "service_role";

grant update on table "public"."Games" to "service_role";

grant delete on table "public"."JoinedGame" to "anon";

grant insert on table "public"."JoinedGame" to "anon";

grant references on table "public"."JoinedGame" to "anon";

grant select on table "public"."JoinedGame" to "anon";

grant trigger on table "public"."JoinedGame" to "anon";

grant truncate on table "public"."JoinedGame" to "anon";

grant update on table "public"."JoinedGame" to "anon";

grant delete on table "public"."JoinedGame" to "authenticated";

grant insert on table "public"."JoinedGame" to "authenticated";

grant references on table "public"."JoinedGame" to "authenticated";

grant select on table "public"."JoinedGame" to "authenticated";

grant trigger on table "public"."JoinedGame" to "authenticated";

grant truncate on table "public"."JoinedGame" to "authenticated";

grant update on table "public"."JoinedGame" to "authenticated";

grant delete on table "public"."JoinedGame" to "service_role";

grant insert on table "public"."JoinedGame" to "service_role";

grant references on table "public"."JoinedGame" to "service_role";

grant select on table "public"."JoinedGame" to "service_role";

grant trigger on table "public"."JoinedGame" to "service_role";

grant truncate on table "public"."JoinedGame" to "service_role";

grant update on table "public"."JoinedGame" to "service_role";

grant delete on table "public"."SessionNotes" to "anon";

grant insert on table "public"."SessionNotes" to "anon";

grant references on table "public"."SessionNotes" to "anon";

grant select on table "public"."SessionNotes" to "anon";

grant trigger on table "public"."SessionNotes" to "anon";

grant truncate on table "public"."SessionNotes" to "anon";

grant update on table "public"."SessionNotes" to "anon";

grant delete on table "public"."SessionNotes" to "authenticated";

grant insert on table "public"."SessionNotes" to "authenticated";

grant references on table "public"."SessionNotes" to "authenticated";

grant select on table "public"."SessionNotes" to "authenticated";

grant trigger on table "public"."SessionNotes" to "authenticated";

grant truncate on table "public"."SessionNotes" to "authenticated";

grant update on table "public"."SessionNotes" to "authenticated";

grant delete on table "public"."SessionNotes" to "service_role";

grant insert on table "public"."SessionNotes" to "service_role";

grant references on table "public"."SessionNotes" to "service_role";

grant select on table "public"."SessionNotes" to "service_role";

grant trigger on table "public"."SessionNotes" to "service_role";

grant truncate on table "public"."SessionNotes" to "service_role";

grant update on table "public"."SessionNotes" to "service_role";

grant delete on table "public"."Users" to "anon";

grant insert on table "public"."Users" to "anon";

grant references on table "public"."Users" to "anon";

grant select on table "public"."Users" to "anon";

grant trigger on table "public"."Users" to "anon";

grant truncate on table "public"."Users" to "anon";

grant update on table "public"."Users" to "anon";

grant delete on table "public"."Users" to "authenticated";

grant insert on table "public"."Users" to "authenticated";

grant references on table "public"."Users" to "authenticated";

grant select on table "public"."Users" to "authenticated";

grant trigger on table "public"."Users" to "authenticated";

grant truncate on table "public"."Users" to "authenticated";

grant update on table "public"."Users" to "authenticated";

grant delete on table "public"."Users" to "service_role";

grant insert on table "public"."Users" to "service_role";

grant references on table "public"."Users" to "service_role";

grant select on table "public"."Users" to "service_role";

grant trigger on table "public"."Users" to "service_role";

grant truncate on table "public"."Users" to "service_role";

grant update on table "public"."Users" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."Games"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all authenticated users"
on "public"."Games"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for authenticated users only"
on "public"."Games"
as permissive
for update
to authenticated
using (true)
with check (true);


create policy "Enable insert for authenticated users only"
on "public"."JoinedGame"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."JoinedGame"
as permissive
for select
to public
using (true);


create policy "Enable insert for authenticated users only"
on "public"."SessionNotes"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read for authenticated users only"
on "public"."SessionNotes"
as permissive
for select
to authenticated
using (true);


create policy "Enable update for authenticated users"
on "public"."SessionNotes"
as permissive
for update
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."Users"
as permissive
for select
to public
using (true);



